/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  golangSidebar: [
    {
      type: 'category',
      label: 'GoLang',
      link: {
        type: 'generated-index',
        title: 'GoLang',
        description: 'Learn about GoLang!',
        keywords: ['golang', 'go'],
      },
      items: [{ type: 'autogenerated', dirName: 'golang' }],
    },
  ],
  cppSidebar: [
    {
      type: 'category',
      label: 'C++',
      link: {
        type: 'generated-index',
        title: 'C++',
        description: 'Learn about C++!',
        keywords: ['cpp', 'c++'],
      },
      items: [{ type: 'autogenerated', dirName: 'cpp' }],
    },
  ],
  algorithmSidebar: [
    {
      type: 'category',
      label: 'Algorithm',
      link: {
        type: 'generated-index',
        title: 'Algorithm',
        description: 'Learn about Algorithm!',
        keywords: ['dp','binary search'],
      },
      items: [{ type: 'autogenerated', dirName: 'algorithm' }],
    },
  ],
  storageSidebar: [
    {
      type: 'category',
      label: 'Storage',
      link: {
        type: 'generated-index',
        title: 'Storage',
        description: 'Learn about Storage!',
        keywords: ['redis','mysql'],
      },
      items: [{ type: 'autogenerated', dirName: 'storage' }],
    },
  ],
  designSidebar: [
    {
      type: 'category',
      label: 'Design',
      link: {
        type: 'generated-index',
        title: 'Design',
        description: 'Learn about System Design!',
        keywords: ['design', 'pattern'],
      },
      items: [{ type: 'autogenerated', dirName: 'design' }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
